apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cicd
rules:
  - apiGroups: ["", "apps", "networking.k8s.io"]
    resources: ["namespaces", "deployments", "replicasets", "ingresses", "services", "secrets"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
